"""rebuild db

Revision ID: 849cv82914qw
Revises: 459gp79265ef
Create Date: 2023-09-11 01:50:21.455825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849cv82914qw'
down_revision = '459gp79265ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###